version: '2'

services:
  ftp:
    image: ivonet/ftp
    ports:
    - "11021:21"
    - "30000-30009:30000-30009"
    volumes:
    - ./docker/ftp/passwd:/etc/pure-ftpd/passwd
    - ./test-data/ftp:/home/ftpusers

#  mysql:
#    image: ivonet/mysql:latest
#    volumes:
#      - ./docker/mysql/setup:/docker-entrypoint-initdb.d
#      - ./docker/volumes/mysql:/testdata
#      - mysql-data:/var/lib/mysql
#    ports:
#      - "3306:3306"
#    environment:
#        - MYSQL_ROOT_PASSWORD=secret
#
#  activemq:
#    image: registry.gitlabcd.itv.local/vod-squad/activemq
#    ports:
#    - "8161:8161"
#    - "61616:61616"
#    - "61613:61613"
#    environment:
#    - ACTIVEMQ_MIN_MEMORY=512
#    - ACTIVEMQ_MAX_MEMORY=2048
#    - ACTIVEMQ_ENABLED_AUTH=true
#    - ACTIVEMQ_ADMIN_LOGIN=admin
#    - ACTIVEMQ_ADMIN_PASSWORD=secret
#    volumes:
#    - ./volumes/log/activemq:/var/log/activemq
#
#
#volumes:
#  mysql-data:
#    driver: local