version: '2'

services:
  mysql:
    image: ivonet/mysql:latest
    volumes:
      - ./docker/mysql/setup:/docker-entrypoint-initdb.d
      - ./docker/volumes/mysql:/testdata
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=secret

volumes:
  mysql-data:
    driver: local